/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.AtomicExpressionEnum;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atomic Expression Enum</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.AtomicExpressionEnumImpl#getEnumeration <em>Enumeration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.AtomicExpressionEnumImpl#getEnumItem <em>Enum Item</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtomicExpressionEnumImpl extends ExpressionImpl implements AtomicExpressionEnum
{
  /**
   * The default value of the '{@link #getEnumeration() <em>Enumeration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumeration()
   * @generated
   * @ordered
   */
  protected static final String ENUMERATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnumeration() <em>Enumeration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumeration()
   * @generated
   * @ordered
   */
  protected String enumeration = ENUMERATION_EDEFAULT;

  /**
   * The default value of the '{@link #getEnumItem() <em>Enum Item</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumItem()
   * @generated
   * @ordered
   */
  protected static final String ENUM_ITEM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnumItem() <em>Enum Item</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumItem()
   * @generated
   * @ordered
   */
  protected String enumItem = ENUM_ITEM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtomicExpressionEnumImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ATOMIC_EXPRESSION_ENUM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEnumeration()
  {
    return enumeration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnumeration(String newEnumeration)
  {
    String oldEnumeration = enumeration;
    enumeration = newEnumeration;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUMERATION, oldEnumeration, enumeration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEnumItem()
  {
    return enumItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnumItem(String newEnumItem)
  {
    String oldEnumItem = enumItem;
    enumItem = newEnumItem;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUM_ITEM, oldEnumItem, enumItem));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUMERATION:
        return getEnumeration();
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUM_ITEM:
        return getEnumItem();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUMERATION:
        setEnumeration((String)newValue);
        return;
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUM_ITEM:
        setEnumItem((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUMERATION:
        setEnumeration(ENUMERATION_EDEFAULT);
        return;
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUM_ITEM:
        setEnumItem(ENUM_ITEM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUMERATION:
        return ENUMERATION_EDEFAULT == null ? enumeration != null : !ENUMERATION_EDEFAULT.equals(enumeration);
      case MyDslPackage.ATOMIC_EXPRESSION_ENUM__ENUM_ITEM:
        return ENUM_ITEM_EDEFAULT == null ? enumItem != null : !ENUM_ITEM_EDEFAULT.equals(enumItem);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (enumeration: ");
    result.append(enumeration);
    result.append(", enumItem: ");
    result.append(enumItem);
    result.append(')');
    return result.toString();
  }

} //AtomicExpressionEnumImpl
