/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.OtherDeclaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Other Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OtherDeclarationImpl extends DeclarationImpl implements OtherDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OtherDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OTHER_DECLARATION;
  }

} //OtherDeclarationImpl
