/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PAtomPredicate;
import org.xtext.example.mydsl.myDsl.PredicateFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PAtom Predicate</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.PAtomPredicateImpl#getPredicateFunction <em>Predicate Function</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PAtomPredicateImpl extends PropositionImpl implements PAtomPredicate
{
  /**
   * The cached value of the '{@link #getPredicateFunction() <em>Predicate Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredicateFunction()
   * @generated
   * @ordered
   */
  protected PredicateFunction predicateFunction;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PAtomPredicateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PATOM_PREDICATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunction getPredicateFunction()
  {
    return predicateFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPredicateFunction(PredicateFunction newPredicateFunction, NotificationChain msgs)
  {
    PredicateFunction oldPredicateFunction = predicateFunction;
    predicateFunction = newPredicateFunction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION, oldPredicateFunction, newPredicateFunction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPredicateFunction(PredicateFunction newPredicateFunction)
  {
    if (newPredicateFunction != predicateFunction)
    {
      NotificationChain msgs = null;
      if (predicateFunction != null)
        msgs = ((InternalEObject)predicateFunction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION, null, msgs);
      if (newPredicateFunction != null)
        msgs = ((InternalEObject)newPredicateFunction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION, null, msgs);
      msgs = basicSetPredicateFunction(newPredicateFunction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION, newPredicateFunction, newPredicateFunction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION:
        return basicSetPredicateFunction(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION:
        return getPredicateFunction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION:
        setPredicateFunction((PredicateFunction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION:
        setPredicateFunction((PredicateFunction)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PATOM_PREDICATE__PREDICATE_FUNCTION:
        return predicateFunction != null;
    }
    return super.eIsSet(featureID);
  }

} //PAtomPredicateImpl
