/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.Event;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PointAtomContractEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Point Atom Contract Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.PointAtomContractEventImpl#getContractEvent <em>Contract Event</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PointAtomContractEventImpl extends PointExpressionImpl implements PointAtomContractEvent
{
  /**
   * The cached value of the '{@link #getContractEvent() <em>Contract Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContractEvent()
   * @generated
   * @ordered
   */
  protected Event contractEvent;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PointAtomContractEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.POINT_ATOM_CONTRACT_EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event getContractEvent()
  {
    return contractEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContractEvent(Event newContractEvent, NotificationChain msgs)
  {
    Event oldContractEvent = contractEvent;
    contractEvent = newContractEvent;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT, oldContractEvent, newContractEvent);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContractEvent(Event newContractEvent)
  {
    if (newContractEvent != contractEvent)
    {
      NotificationChain msgs = null;
      if (contractEvent != null)
        msgs = ((InternalEObject)contractEvent).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT, null, msgs);
      if (newContractEvent != null)
        msgs = ((InternalEObject)newContractEvent).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT, null, msgs);
      msgs = basicSetContractEvent(newContractEvent, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT, newContractEvent, newContractEvent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT:
        return basicSetContractEvent(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT:
        return getContractEvent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT:
        setContractEvent((Event)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT:
        setContractEvent((Event)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.POINT_ATOM_CONTRACT_EVENT__CONTRACT_EVENT:
        return contractEvent != null;
    }
    return super.eIsSet(featureID);
  }

} //PointAtomContractEventImpl
