/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PowerState;
import org.xtext.example.mydsl.myDsl.PowerWrapper;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Power State</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.PowerStateImpl#getPowerVariable <em>Power Variable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PowerStateImpl extends SituationImpl implements PowerState
{
  /**
   * The cached value of the '{@link #getPowerVariable() <em>Power Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowerVariable()
   * @generated
   * @ordered
   */
  protected PowerWrapper powerVariable;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PowerStateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.POWER_STATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PowerWrapper getPowerVariable()
  {
    if (powerVariable != null && powerVariable.eIsProxy())
    {
      InternalEObject oldPowerVariable = (InternalEObject)powerVariable;
      powerVariable = (PowerWrapper)eResolveProxy(oldPowerVariable);
      if (powerVariable != oldPowerVariable)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.POWER_STATE__POWER_VARIABLE, oldPowerVariable, powerVariable));
      }
    }
    return powerVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PowerWrapper basicGetPowerVariable()
  {
    return powerVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPowerVariable(PowerWrapper newPowerVariable)
  {
    PowerWrapper oldPowerVariable = powerVariable;
    powerVariable = newPowerVariable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.POWER_STATE__POWER_VARIABLE, oldPowerVariable, powerVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.POWER_STATE__POWER_VARIABLE:
        if (resolve) return getPowerVariable();
        return basicGetPowerVariable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.POWER_STATE__POWER_VARIABLE:
        setPowerVariable((PowerWrapper)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.POWER_STATE__POWER_VARIABLE:
        setPowerVariable((PowerWrapper)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.POWER_STATE__POWER_VARIABLE:
        return powerVariable != null;
    }
    return super.eIsSet(featureID);
  }

} //PowerStateImpl
