/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PredicateFunctionCannotBeAssigned;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Predicate Function Cannot Be Assigned</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PredicateFunctionCannotBeAssignedImpl extends OtherFunctionImpl implements PredicateFunctionCannotBeAssigned
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PredicateFunctionCannotBeAssignedImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PREDICATE_FUNCTION_CANNOT_BE_ASSIGNED;
  }

} //PredicateFunctionCannotBeAssignedImpl
