/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.hello_world.ui.internal.Hello_worldActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Hello_worldActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
