/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Expression Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AtomicExpressionParameter#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAtomicExpressionParameter()
 * @model
 * @generated
 */
public interface AtomicExpressionParameter extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Ref)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAtomicExpressionParameter_Value()
   * @model containment="true"
   * @generated
   */
  Ref getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.AtomicExpressionParameter#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Ref value);

} // AtomicExpressionParameter
