/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getContractAsset <em>Contract Asset</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract()
 * @model
 * @generated
 */
public interface Contract extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Contract Asset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contract Asset</em>' attribute.
   * @see #setContractAsset(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_ContractAsset()
   * @model
   * @generated
   */
  String getContractAsset();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getContractAsset <em>Contract Asset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contract Asset</em>' attribute.
   * @see #getContractAsset()
   * @generated
   */
  void setContractAsset(String value);

} // Contract
