/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interval Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IntervalFunction#getArg1 <em>Arg1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IntervalFunction#getArg2 <em>Arg2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIntervalFunction()
 * @model
 * @generated
 */
public interface IntervalFunction extends IntervalExpression
{
  /**
   * Returns the value of the '<em><b>Arg1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg1</em>' containment reference.
   * @see #setArg1(PointExpression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIntervalFunction_Arg1()
   * @model containment="true"
   * @generated
   */
  PointExpression getArg1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IntervalFunction#getArg1 <em>Arg1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg1</em>' containment reference.
   * @see #getArg1()
   * @generated
   */
  void setArg1(PointExpression value);

  /**
   * Returns the value of the '<em><b>Arg2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg2</em>' containment reference.
   * @see #setArg2(PointExpression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIntervalFunction_Arg2()
   * @model containment="true"
   * @generated
   */
  PointExpression getArg2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IntervalFunction#getArg2 <em>Arg2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg2</em>' containment reference.
   * @see #getArg2()
   * @generated
   */
  void setArg2(PointExpression value);

} // IntervalFunction
