/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getEntities <em>Entities</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getLogic <em>Logic</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference.
   * @see #setEntities(Entities)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_Entities()
   * @model containment="true"
   * @generated
   */
  Entities getEntities();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Model#getEntities <em>Entities</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entities</em>' containment reference.
   * @see #getEntities()
   * @generated
   */
  void setEntities(Entities value);

  /**
   * Returns the value of the '<em><b>Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic</em>' containment reference.
   * @see #setLogic(Logic)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_Logic()
   * @model containment="true"
   * @generated
   */
  Logic getLogic();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Model#getLogic <em>Logic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logic</em>' containment reference.
   * @see #getLogic()
   * @generated
   */
  void setLogic(Logic value);

} // Model
