/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>One Arg Math Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOneArgMathFunction()
 * @model
 * @generated
 */
public interface OneArgMathFunction extends FunctionCall
{
} // OneArgMathFunction
