/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAtom Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PAtomFunction#getFunction <em>Function</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPAtomFunction()
 * @model
 * @generated
 */
public interface PAtomFunction extends Proposition
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference.
   * @see #setFunction(OtherFunction)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPAtomFunction_Function()
   * @model containment="true"
   * @generated
   */
  OtherFunction getFunction();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PAtomFunction#getFunction <em>Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' containment reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(OtherFunction value);

} // PAtomFunction
