/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PF Obligation Suspended</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PFObligationSuspended#getNorm <em>Norm</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPFObligationSuspended()
 * @model
 * @generated
 */
public interface PFObligationSuspended extends PowerFunction
{
  /**
   * Returns the value of the '<em><b>Norm</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Norm</em>' reference.
   * @see #setNorm(ObligationWrapper)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPFObligationSuspended_Norm()
   * @model
   * @generated
   */
  ObligationWrapper getNorm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PFObligationSuspended#getNorm <em>Norm</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Norm</em>' reference.
   * @see #getNorm()
   * @generated
   */
  void setNorm(ObligationWrapper value);

} // PFObligationSuspended
