/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Power Wrapper</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PowerWrapper#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PowerWrapper#getPow <em>Pow</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPowerWrapper()
 * @model
 * @generated
 */
public interface PowerWrapper extends Command
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPowerWrapper_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PowerWrapper#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Pow</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pow</em>' containment reference.
   * @see #setPow(Power)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPowerWrapper_Pow()
   * @model containment="true"
   * @generated
   */
  Power getPow();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PowerWrapper#getPow <em>Pow</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pow</em>' containment reference.
   * @see #getPow()
   * @generated
   */
  void setPow(Power value);

} // PowerWrapper
