/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Function Occurs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PredicateFunctionOccurs#getSituation <em>Situation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PredicateFunctionOccurs#getInterval <em>Interval</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicateFunctionOccurs()
 * @model
 * @generated
 */
public interface PredicateFunctionOccurs extends PredicateFunction
{
  /**
   * Returns the value of the '<em><b>Situation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Situation</em>' containment reference.
   * @see #setSituation(Situation)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicateFunctionOccurs_Situation()
   * @model containment="true"
   * @generated
   */
  Situation getSituation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PredicateFunctionOccurs#getSituation <em>Situation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Situation</em>' containment reference.
   * @see #getSituation()
   * @generated
   */
  void setSituation(Situation value);

  /**
   * Returns the value of the '<em><b>Interval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interval</em>' containment reference.
   * @see #setInterval(Interval)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicateFunctionOccurs_Interval()
   * @model containment="true"
   * @generated
   */
  Interval getInterval();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PredicateFunctionOccurs#getInterval <em>Interval</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interval</em>' containment reference.
   * @see #getInterval()
   * @generated
   */
  void setInterval(Interval value);

} // PredicateFunctionOccurs
