/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Function Cannot Be Assigned</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredicateFunctionCannotBeAssigned()
 * @model
 * @generated
 */
public interface PredicateFunctionCannotBeAssigned extends OtherFunction
{
} // PredicateFunctionCannotBeAssigned
