/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Three Arg Date Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ThreeArgDateFunction#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ThreeArgDateFunction#getTimeUnit <em>Time Unit</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getThreeArgDateFunction()
 * @model
 * @generated
 */
public interface ThreeArgDateFunction extends FunctionCall
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getThreeArgDateFunction_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ThreeArgDateFunction#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

  /**
   * Returns the value of the '<em><b>Time Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Unit</em>' attribute.
   * @see #setTimeUnit(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getThreeArgDateFunction_TimeUnit()
   * @model
   * @generated
   */
  String getTimeUnit();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ThreeArgDateFunction#getTimeUnit <em>Time Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Unit</em>' attribute.
   * @see #getTimeUnit()
   * @generated
   */
  void setTimeUnit(String value);

} // ThreeArgDateFunction
